databases:
  - name: bidding
    databaseName: bidding
    user: bidding

services:
  - type: web
    name: online-bidding
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bidding
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
